# after-login-command = []
# after-startup-command = []
start-at-login = true

enable-normalization-flatten-containers = true
enable-normalization-opposite-orientation-for-nested-containers = true

# TODO: learn what is this?
# non-empty-workspaces-root-containers-layout-on-startup = 'smart'

accordion-padding = 0
default-root-container-layout = 'accordion'
default-root-container-orientation = 'auto'
key-mapping.preset = 'qwerty'

on-focused-monitor-changed = ['move-mouse monitor-lazy-center']
on-focus-changed = ['move-mouse window-lazy-center']

[gaps]
inner.horizontal = 8
inner.vertical = 8
outer.bottom = 0
outer.left = 0
outer.right = 0
outer.top = 0

[mode.main.binding]
# TODO: come up with a more intuitive keybinding for this?
alt-slash = 'layout tiles horizontal vertical'
alt-comma = 'layout accordion horizontal vertical'

# TODO: integrate with tmux vim navigation
alt-shift-h = 'focus left'
alt-shift-j = 'focus down'
alt-shift-k = 'focus up'
alt-shift-l = 'focus right'

# TODO: is this helpful? How does it work?
# alt-shift-n = 'split opposite'
alt-shift-minus = 'resize smart -100'
alt-shift-equal = 'resize smart +100'

alt-tab = 'workspace-back-and-forth'
alt-shift-tab = 'move-workspace-to-monitor --wrap-around next'

alt-shift-semicolon = 'mode layout'

alt-shift-z = 'mode move'

[mode.move.binding]
esc = ['mode main']
w = ['move-node-to-workspace w', 'workspace w']
a = ['move-node-to-workspace a', 'workspace a']
s = ['move-node-to-workspace s', 'workspace s']
d = ['move-node-to-workspace d', 'workspace d']
g = ['move-node-to-workspace g', 'workspace g']

# TODO: come up with a mode that works for me (resizing, moving?)
[mode.layout.binding]
esc = ['mode main']
e = 'layout accordion horizontal vertical'
h = 'move left'
j = 'move down'
k = 'move up'
l = 'move right'
alt-h = 'join-with left'
alt-j = 'join-with down'
alt-k = 'join-with up'
alt-l = 'join-with right'
f = 'fullscreen'
0 = ['flatten-workspace-tree', 'mode main']
g = ['layout floating tiling', 'mode main']
minus = 'resize smart -100'
equal = 'resize smart +100'

[workspace-to-monitor-force-assignment]
g = ['secondary']

[[on-window-detected]]
if.app-id = 'com.github.wez.wezterm'
run = ['layout tiling', 'move-node-to-workspace a']

[[on-window-detected]]
if.app-id = 'md.obsidian'
run = ['layout tiling', 'move-node-to-workspace s']

[[on-window-detected]]
if.app-id = 'com.hnc.Discord'
run = ['layout tiling', 'move-node-to-workspace d']

[[on-window-detected]]
if.app-id = 'company.thebrowser.Browser'
run = ['layout tiling', 'move-node-to-workspace w']

[[on-window-detected]]
if.app-id = 'com.apple.MobileSMS'
run = ['layout tiling', 'move-node-to-workspace m']

[[on-window-detected]]
if.app-id = 'com.obsproject.obs-studio'
run = ['layout tiling', 'move-node-to-workspace o']

[[on-window-detected]]
if.app-id = 'com.google.Chrome'
run = ['layout tiling', 'move-node-to-workspace g']

# zoom to move to `s` and tile top 1/3
